// ===== APP STATE =====
const STATE = {
  level: 'B1',
  dailyGoal: 20,
  darkMode: false,
  streak: 7,
  totalDays: 23,
  boxes: { 1:18, 2:24, 3:31, 4:22, 5:16, 6:9 },
  grammarStats: {
    'Past Simple':       { attempts:31, correct:25 },
    'Present Perfect':   { attempts:22, correct:10 },
    'Passive Voice':     { attempts:18, correct: 9 },
    'Conditionals':      { attempts:15, correct: 9 },
    'Modal Verbs':       { attempts: 9, correct: 6 },
  },
  todayNew: 12,
  todayReview: 8,
  todayGrammar: 5,
  todayAccuracy: 84,
  velocity7: [8,15,20,12,18,22,12],
  accuracy30: {
    vocab:   [58,60,62,59,63,65,64,67,66,68,70,69,71,72,70,73,74,72,75,76,75,77,76,78,77,79,78,80,79,78],
    grammar: [42,44,43,46,45,47,48,46,49,50,49,51,50,52,53,51,54,53,55,56,54,57,56,58,57,59,60,61,62,65],
    reading: [50,52,51,54,53,55,56,54,57,58,57,59,60,61,59,62,63,61,64,65,63,66,67,65,68,69,67,70,71,72],
  },
};

// ===== GRAMMAR DATABASE =====
const GRAMMAR_DB = {
  'Past Simple': {
    use: 'เหตุการณ์ที่เกิดขึ้นและจบแล้วในอดีต มักมีคำบอกเวลาเช่น yesterday, last year, ago',
    structure: 'Subject + V2 (past form)',
    negative: 'Subject + did not + V1',
    question: 'Did + Subject + V1?',
    examples: [
      'She achieved her goal last year.',
      'They negotiated a deal in 2022.',
      'He did not contribute to the project.',
    ],
  },
  'Present Perfect': {
    use: 'เหตุการณ์ที่เกิดในอดีตแต่ยังเชื่อมกับปัจจุบัน หรือประสบการณ์ มักมี since, for, already, yet',
    structure: 'Subject + have / has + V3',
    negative: 'Subject + have/has + not + V3',
    question: 'Have / Has + Subject + V3?',
    examples: [
      'She has achieved a lot in her career.',
      'They have negotiated successfully since 2020.',
      'He has not contributed any ideas yet.',
    ],
  },
  'Passive Voice': {
    use: 'เน้นผลลัพธ์หรือสิ่งที่ถูกกระทำ ไม่เน้นผู้กระทำ ใช้บ่อยในงานเขียนวิชาการและข่าว',
    structure: 'Subject + was / were + V3',
    negative: 'Subject + was/were + not + V3',
    question: 'Was / Were + Subject + V3?',
    examples: [
      'The goal was achieved by the entire team.',
      'A new deal was negotiated last month.',
      'Many ideas were contributed by the students.',
    ],
  },
  'Conditionals': {
    use: 'Second Conditional — สถานการณ์สมมติที่ไม่น่าเป็นจริงในปัจจุบันหรืออนาคต',
    structure: 'If + Subject + V2,  Subject + would + V1',
    negative: 'If + Subject + did not + V1,  Subject + would not + V1',
    question: 'What would happen if...?',
    examples: [
      'If she persisted, she would achieve her goal.',
      'If they negotiated better, they would win.',
      'If he contributed more, the team would improve.',
    ],
  },
  'Modal Verbs': {
    use: 'แสดงความสามารถ ความเป็นไปได้ คำแนะนำ หรือความจำเป็น',
    structure: 'Subject + modal + V1  (modal = can/could/should/must/might/may)',
    negative: 'Subject + modal + not + V1',
    question: 'Modal + Subject + V1?',
    examples: [
      'You should emphasize the key points.',
      'She can achieve anything with effort.',
      'They might negotiate a better deal.',
    ],
  },
  'Future Simple': {
    use: 'การกระทำหรือเหตุการณ์ในอนาคต การตัดสินใจทันที หรือการคาดการณ์',
    structure: 'Subject + will + V1',
    negative: 'Subject + will not (won\'t) + V1',
    question: 'Will + Subject + V1?',
    examples: [
      'She will achieve her target next month.',
      'They will negotiate the terms tomorrow.',
      'He will not contribute if he is busy.',
    ],
  },
  'Present Continuous': {
    use: 'การกระทำที่กำลังเกิดขึ้นตอนนี้ หรือแผนในอนาคตที่แน่นอน',
    structure: 'Subject + am/is/are + V-ing',
    negative: 'Subject + am/is/are + not + V-ing',
    question: 'Am/Is/Are + Subject + V-ing?',
    examples: [
      'She is currently analyzing the data.',
      'They are negotiating a new agreement.',
      'He is not contributing to the discussion.',
    ],
  },
};

// ===== VOCABULARY DATABASE (B1 core — 40 words) =====
// Full version will load from Oxford 3000 JSON
const WORDS = [{
    word: 'achieve',
    level: 'B1',
    partOfSpeech: ['verb [T]'],
    ipa_uk: '/əˈtʃiːv/',
    ipa_us: '/əˈtʃiːv/',
    meanings: [
      { pos: 'verb [T]', en: 'To successfully reach a goal or complete something through effort.', th: 'บรรลุ, ทำสำเร็จ' },
    ],
    antonyms: ['fail', 'lose'],
    examples: [
      'She achieved her dream of becoming a pilot after years of training.',
      'The team achieved excellent results through consistent hard work.',
      'Nothing great can be achieved without dedication and patience.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'adapt',
    level: 'B1',
    partOfSpeech: ['verb [I]', 'verb [T]'],
    ipa_uk: '/əˈdæpt/',
    ipa_us: '/əˈdæpt/',
    meanings: [
      { pos: 'verb [I]', en: 'To change your behaviour to deal with a new situation.', th: 'ปรับตัว' },
      { pos: 'verb [T]', en: 'To change something so that it works in a different situation.', th: 'ดัดแปลง' },
    ],
    antonyms: ['resist', 'reject'],
    examples: [
      'It took her several months to adapt to life in a new country.',
      'The director adapted the novel into a successful film.',
      'Animals that cannot adapt to climate change may become extinct.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'adequate',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/ˈædɪkwət/',
    ipa_us: '/ˈædɪkwət/',
    meanings: [
      { pos: 'adjective', en: 'Enough in quantity or acceptable in quality for a particular purpose.', th: 'เพียงพอ, พอใช้ได้' },
    ],
    antonyms: ['inadequate', 'insufficient'],
    examples: [
      'The shelter provided adequate protection from the rain.',
      'Her preparation was adequate but not exceptional.',
      'We must ensure all students have adequate access to learning materials.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'affect',
    level: 'B1',
    partOfSpeech: ['verb [T]'],
    ipa_uk: '/əˈfekt/',
    ipa_us: '/əˈfekt/',
    meanings: [
      { pos: 'verb [T]', en: 'To have an influence on someone or something and cause a change.', th: 'ส่งผลต่อ, มีผลกระทบต่อ' },
    ],
    antonyms: ['ignore', 'exclude'],
    examples: [
      'The heavy rain affected the outdoor concert severely.',
      'Stress can significantly affect both your physical and mental health.',
      'Rising fuel prices have affected the cost of everyday goods.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'ambition',
    level: 'B1',
    partOfSpeech: ['noun [C]', 'noun [U]'],
    ipa_uk: '/æmˈbɪʃən/',
    ipa_us: '/æmˈbɪʃən/',
    meanings: [
      { pos: 'noun [C]', en: 'A strong desire to achieve a specific goal.', th: 'ความทะเยอทะยาน, เป้าหมายที่ต้องการ' },
      { pos: 'noun [U]', en: 'The general quality of being determined to succeed.', th: 'ความมุ่งมั่น, ความทะเยอทะยาน' },
    ],
    antonyms: ['laziness', 'indifference'],
    examples: [
      'Her ambition is to run her own company before she turns thirty.',
      'He has always had great ambition and rarely gives up on anything.',
      'Without ambition, it is difficult to push yourself beyond your limits.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'apparent',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/əˈpærənt/',
    ipa_us: '/əˈpærənt/',
    meanings: [
      { pos: 'adjective', en: 'Easy to see or understand; clearly visible or obvious.', th: 'ชัดเจน, เห็นได้ชัด' },
      { pos: 'adjective', en: 'Seeming to be true but possibly not actually so.', th: 'ที่ดูเหมือนจะเป็น, ที่ปรากฏ' },
    ],
    antonyms: ['hidden', 'unclear'],
    examples: [
      'It was apparent from her expression that she was deeply upset.',
      'The apparent cause of the fire was an electrical fault.',
      'His enthusiasm for the project was apparent to everyone in the room.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'arrange',
    level: 'B1',
    partOfSpeech: ['verb [T]', 'verb [I]'],
    ipa_uk: '/əˈreɪndʒ/',
    ipa_us: '/əˈreɪndʒ/',
    meanings: [
      { pos: 'verb [T]', en: 'To plan or organise something in advance.', th: 'จัดการ, จัดเตรียม, นัดหมาย' },
      { pos: 'verb [T]', en: 'To put things in a particular order or position.', th: 'จัดเรียง, จัดวาง' },
    ],
    antonyms: ['cancel', 'disorganise'],
    examples: [
      'She arranged a meeting with the team for the following Monday.',
      'He carefully arranged the books on the shelf by subject.',
      'Can you arrange for someone to pick her up from the airport?',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'attitude',
    level: 'B1',
    partOfSpeech: ['noun [C]', 'noun [U]'],
    ipa_uk: '/ˈætɪtjuːd/',
    ipa_us: '/ˈætɪtuːd/',
    meanings: [
      { pos: 'noun [C/U]', en: 'The way you think and feel about someone or something, shown in your behaviour.', th: 'ทัศนคติ, ท่าที' },
    ],
    antonyms: ['indifference'],
    examples: [
      'She always approaches problems with a positive attitude.',
      'His attitude towards learning changed dramatically after the experience.',
      'A good attitude can make a significant difference in the workplace.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'avoid',
    level: 'B1',
    partOfSpeech: ['verb [T]'],
    ipa_uk: '/əˈvɔɪd/',
    ipa_us: '/əˈvɔɪd/',
    meanings: [
      { pos: 'verb [T]', en: 'To stay away from someone or something, or to prevent something from happening.', th: 'หลีกเลี่ยง, เลี่ยง' },
    ],
    antonyms: ['seek', 'confront'],
    examples: [
      'She took a different route to avoid the heavy traffic.',
      'Try to avoid making promises you cannot keep.',
      'He avoided eye contact during the entire conversation.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'aware',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/əˈweə/',
    ipa_us: '/əˈwer/',
    meanings: [
      { pos: 'adjective', en: 'Knowing that something exists or is happening.', th: 'ตระหนัก, รู้ตัว, รับรู้' },
    ],
    antonyms: ['unaware', 'ignorant'],
    examples: [
      'Are you aware of the changes to the company policy?',
      'She became aware of a strange smell coming from the kitchen.',
      'Being aware of your surroundings is important for personal safety.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'benefit',
    level: 'B1',
    partOfSpeech: ['noun [C]', 'noun [U]', 'verb [I]', 'verb [T]'],
    ipa_uk: '/ˈbenɪfɪt/',
    ipa_us: '/ˈbenɪfɪt/',
    meanings: [
      { pos: 'noun [C/U]', en: 'An advantage or something that has a helpful or good effect.', th: 'ประโยชน์, ผลดี' },
      { pos: 'verb [I/T]', en: 'To be helped by something or to help someone.', th: 'ได้รับประโยชน์, เป็นประโยชน์ต่อ' },
    ],
    antonyms: ['harm', 'disadvantage'],
    examples: [
      'Regular exercise has many benefits for both body and mind.',
      'The new law will benefit thousands of low-income families.',
      'She benefited greatly from the mentoring programme.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'challenge',
    level: 'B1',
    partOfSpeech: ['noun [C]', 'verb [T]'],
    ipa_uk: '/ˈtʃælɪndʒ/',
    ipa_us: '/ˈtʃælɪndʒ/',
    meanings: [
      { pos: 'noun [C]', en: 'Something difficult that requires great effort and determination.', th: 'ความท้าทาย, สิ่งที่ยากแต่น่าทำ' },
      { pos: 'verb [T]', en: 'To question whether something is right or to invite someone to compete.', th: 'ท้าทาย, โต้แย้ง' },
    ],
    antonyms: ['ease', 'accept'],
    examples: [
      'Learning a new language is always a rewarding challenge.',
      'She challenged the manager\'s decision in the team meeting.',
      'The young athlete rose to the challenge and broke the national record.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'communicate',
    level: 'B1',
    partOfSpeech: ['verb [I]', 'verb [T]'],
    ipa_uk: '/kəˈmjuːnɪkeɪt/',
    ipa_us: '/kəˈmjuːnɪkeɪt/',
    meanings: [
      { pos: 'verb [I/T]', en: 'To share information, ideas, or feelings with someone using speech, writing, or other methods.', th: 'สื่อสาร, ติดต่อ' },
    ],
    antonyms: ['conceal', 'withhold'],
    examples: [
      'It is essential to communicate clearly when working in a team.',
      'She communicates her ideas effectively through detailed written reports.',
      'Parents should communicate openly with their children about difficult topics.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'concentrate',
    level: 'B1',
    partOfSpeech: ['verb [I]'],
    ipa_uk: '/ˈkɒnsəntreɪt/',
    ipa_us: '/ˈkɑːnsəntreɪt/',
    meanings: [
      { pos: 'verb [I]', en: 'To focus all your attention and effort on a particular task or subject.', th: 'มุ่งความสนใจ, จดจ่อ, ตั้งสมาธิ' },
    ],
    antonyms: ['distract', 'scatter'],
    examples: [
      'It is hard to concentrate when there is too much noise around you.',
      'She concentrated on finishing the report before the deadline.',
      'You need to concentrate fully during the final examination.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'confident',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/ˈkɒnfɪdənt/',
    ipa_us: '/ˈkɑːnfɪdənt/',
    meanings: [
      { pos: 'adjective', en: 'Feeling certain about your own abilities or that something will happen as expected.', th: 'มั่นใจ, มีความเชื่อมั่น' },
    ],
    antonyms: ['insecure', 'uncertain'],
    examples: [
      'She felt confident and well-prepared before the job interview.',
      'He gave a confident and clear presentation to the entire board.',
      'Being confident does not mean you never make mistakes.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'conflict',
    level: 'B1',
    partOfSpeech: ['noun [C]', 'noun [U]', 'verb [I]'],
    ipa_uk: '/ˈkɒnflɪkt/',
    ipa_us: '/ˈkɑːnflɪkt/',
    meanings: [
      { pos: 'noun [C/U]', en: 'A serious disagreement or fight between people or groups.', th: 'ความขัดแย้ง, การปะทะ' },
      { pos: 'verb [I]', en: 'To be different from or oppose something else.', th: 'ขัดแย้งกัน, ไม่สอดคล้องกัน' },
    ],
    antonyms: ['agreement', 'harmony'],
    examples: [
      'The two departments were in conflict over the budget allocation.',
      'His personal values conflicted with the company\'s approach to business.',
      'Resolving conflict through calm discussion is always more effective.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'consequence',
    level: 'B1',
    partOfSpeech: ['noun [C]'],
    ipa_uk: '/ˈkɒnsɪkwəns/',
    ipa_us: '/ˈkɑːnsɪkwəns/',
    meanings: [
      { pos: 'noun [C]', en: 'A result or effect of an action or situation, often negative.', th: 'ผลที่ตามมา, ผลลัพธ์' },
    ],
    antonyms: ['cause', 'origin'],
    examples: [
      'She had to face the consequences of her poor decision.',
      'One consequence of the storm was widespread flooding across the region.',
      'Every action has a consequence, whether positive or negative.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'consistent',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/kənˈsɪstənt/',
    ipa_us: '/kənˈsɪstənt/',
    meanings: [
      { pos: 'adjective', en: 'Always behaving in the same way or having the same quality over time.', th: 'สม่ำเสมอ, สอดคล้องกัน' },
      { pos: 'adjective', en: 'In agreement with something else; not contradicting.', th: 'ที่สอดคล้องกับ, ที่ไม่ขัดแย้ง' },
    ],
    antonyms: ['inconsistent', 'erratic'],
    examples: [
      'Her performance has been consistent throughout the entire season.',
      'The witness\'s account was consistent with the physical evidence.',
      'Being consistent in your study habits leads to better long-term results.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'contribute',
    level: 'B1',
    partOfSpeech: ['verb [I]', 'verb [T]'],
    ipa_uk: '/kənˈtrɪbjuːt/',
    ipa_us: '/kənˈtrɪbjuːt/',
    meanings: [
      { pos: 'verb [I/T]', en: 'To give something such as time, money, or ideas in order to help achieve a result.', th: 'มีส่วนร่วม, ช่วยเหลือ, บริจาค' },
    ],
    antonyms: ['withhold', 'hinder'],
    examples: [
      'Everyone in the team contributed ideas during the brainstorming session.',
      'She contributed a large sum of money to the local charity.',
      'Regular exercise contributes significantly to better mental health.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'creative',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/kriˈeɪtɪv/',
    ipa_us: '/kriˈeɪtɪv/',
    meanings: [
      { pos: 'adjective', en: 'Having the ability to produce new and original ideas or things.', th: 'สร้างสรรค์, มีความคิดริเริ่ม' },
    ],
    antonyms: ['unimaginative', 'conventional'],
    examples: [
      'The children came up with very creative solutions to the problem.',
      'She has always been creative and enjoys painting in her spare time.',
      'Creative thinking is one of the most valued skills in modern workplaces.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'curious',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/ˈkjʊəriəs/',
    ipa_us: '/ˈkjʊriəs/',
    meanings: [
      { pos: 'adjective', en: 'Having a strong desire to know or learn about something.', th: 'อยากรู้อยากเห็น, สงสัย' },
      { pos: 'adjective', en: 'Strange or unusual in a way that attracts attention.', th: 'แปลก, น่าประหลาด' },
    ],
    antonyms: ['indifferent', 'uninterested'],
    examples: [
      'Children are naturally curious about how the world around them works.',
      'She gave him a curious look when he mentioned the strange event.',
      'He was curious about the history of the abandoned building.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'deadline',
    level: 'B1',
    partOfSpeech: ['noun [C]'],
    ipa_uk: '/ˈdedlaɪn/',
    ipa_us: '/ˈdedlaɪn/',
    meanings: [
      { pos: 'noun [C]', en: 'A point in time by which something must be finished or completed.', th: 'กำหนดเวลา, เส้นตาย' },
    ],
    antonyms: ['extension', 'unlimited'],
    examples: [
      'The deadline for submitting your application is this Friday at noon.',
      'She always works best under pressure when a deadline is approaching.',
      'Missing a deadline can seriously damage your professional reputation.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'debate',
    level: 'B1',
    partOfSpeech: ['noun [C]', 'noun [U]', 'verb [I]', 'verb [T]'],
    ipa_uk: '/dɪˈbeɪt/',
    ipa_us: '/dɪˈbeɪt/',
    meanings: [
      { pos: 'noun [C/U]', en: 'A formal discussion in which people express different opinions about a topic.', th: 'การอภิปราย, การถกเถียง' },
      { pos: 'verb [I/T]', en: 'To discuss a topic formally or to consider different options carefully.', th: 'อภิปราย, ถกเถียง, พิจารณา' },
    ],
    antonyms: ['agreement', 'consensus'],
    examples: [
      'The politicians took part in a live debate broadcast on national television.',
      'Students debated the causes of climate change for over an hour.',
      'She debated whether to accept the job offer or stay in her current role.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'decision',
    level: 'B1',
    partOfSpeech: ['noun [C]'],
    ipa_uk: '/dɪˈsɪʒən/',
    ipa_us: '/dɪˈsɪʒən/',
    meanings: [
      { pos: 'noun [C]', en: 'A choice that you make after thinking carefully about several possibilities.', th: 'การตัดสินใจ, ข้อสรุป' },
    ],
    antonyms: ['indecision', 'hesitation'],
    examples: [
      'Choosing a career is one of the most important decisions you will ever make.',
      'The manager made a final decision after consulting the entire team.',
      'She regretted her hasty decision to resign without another job lined up.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'demonstrate',
    level: 'B1',
    partOfSpeech: ['verb [T]', 'verb [I]'],
    ipa_uk: '/ˈdemənstreɪt/',
    ipa_us: '/ˈdemənstreɪt/',
    meanings: [
      { pos: 'verb [T]', en: 'To show clearly that something exists or is true by giving evidence or examples.', th: 'แสดงให้เห็น, พิสูจน์' },
      { pos: 'verb [T]', en: 'To show how something works or is done.', th: 'สาธิต, แสดงวิธีการ' },
      { pos: 'verb [I]', en: 'To take part in a public protest.', th: 'ประท้วง, ชุมนุม' },
    ],
    antonyms: ['conceal', 'disprove'],
    examples: [
      'The results clearly demonstrate that the new treatment is effective.',
      'She demonstrated how to use the software step by step.',
      'Thousands of people gathered to demonstrate against the new policy.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'despite',
    level: 'B1',
    partOfSpeech: ['preposition'],
    ipa_uk: '/dɪˈspaɪt/',
    ipa_us: '/dɪˈspaɪt/',
    meanings: [
      { pos: 'preposition', en: 'Used to show that something happened even though something else might have prevented it.', th: 'ทั้งๆ ที่, แม้ว่า' },
    ],
    antonyms: ['because of', 'due to'],
    examples: [
      'She completed the marathon despite having a knee injury.',
      'Despite the heavy rain, the outdoor event continued as planned.',
      'He remained optimistic despite facing many serious setbacks.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'determine',
    level: 'B1',
    partOfSpeech: ['verb [T]'],
    ipa_uk: '/dɪˈtɜːmɪn/',
    ipa_us: '/dɪˈtɜːrmɪn/',
    meanings: [
      { pos: 'verb [T]', en: 'To discover the facts about something or to officially decide something.', th: 'กำหนด, ตัดสิน, ค้นหา' },
      { pos: 'verb [T]', en: 'To be the main factor that controls or influences something.', th: 'เป็นตัวกำหนด, มีผลต่อ' },
    ],
    antonyms: ['ignore', 'neglect'],
    examples: [
      'Investigators worked hard to determine the exact cause of the accident.',
      'Your attitude often determines how successful you will be in life.',
      'The committee will determine whether the project receives funding.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'diverse',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/daɪˈvɜːs/',
    ipa_us: '/daɪˈvɜːrs/',
    meanings: [
      { pos: 'adjective', en: 'Including many different types of people, things, or ideas.', th: 'หลากหลาย, แตกต่างกัน' },
    ],
    antonyms: ['uniform', 'homogeneous'],
    examples: [
      'The city is known for its diverse population and rich cultural heritage.',
      'She has a diverse range of skills that make her a valuable employee.',
      'A diverse team tends to produce more innovative and creative solutions.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'emphasize',
    level: 'B1',
    partOfSpeech: ['verb [T]'],
    ipa_uk: '/ˈemfəsaɪz/',
    ipa_us: '/ˈemfəsaɪz/',
    meanings: [
      { pos: 'verb [T]', en: 'To give special importance or attention to something when speaking or writing.', th: 'เน้น, ย้ำ, ให้ความสำคัญ' },
    ],
    antonyms: ['downplay', 'minimise'],
    examples: [
      'The doctor emphasized the importance of getting enough sleep every night.',
      'She emphasized her key points by speaking more slowly and clearly.',
      'The report emphasizes that immediate action is required to prevent further damage.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'essential',
    level: 'B1',
    partOfSpeech: ['adjective', 'noun [C]'],
    ipa_uk: '/ɪˈsenʃəl/',
    ipa_us: '/ɪˈsenʃəl/',
    meanings: [
      { pos: 'adjective', en: 'Completely necessary and extremely important.', th: 'จำเป็น, สำคัญมาก' },
      { pos: 'noun [C]', en: 'Something that is absolutely necessary.', th: 'สิ่งจำเป็น, สิ่งสำคัญ' },
    ],
    antonyms: ['unnecessary', 'optional'],
    examples: [
      'Clean water and food are essential for human survival.',
      'She packed only the essentials for her two-week trip abroad.',
      'Good communication skills are essential in almost every profession.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'evaluate',
    level: 'B1',
    partOfSpeech: ['verb [T]'],
    ipa_uk: '/ɪˈvæljueɪt/',
    ipa_us: '/ɪˈvæljueɪt/',
    meanings: [
      { pos: 'verb [T]', en: 'To carefully consider or examine something in order to judge its quality or value.', th: 'ประเมิน, ตีค่า, วัดผล' },
    ],
    antonyms: ['ignore', 'overlook'],
    examples: [
      'Teachers evaluate students through a combination of tests and coursework.',
      'We need to evaluate all the risks before making a final decision.',
      'The committee will evaluate each application based on set criteria.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'evident',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/ˈevɪdənt/',
    ipa_us: '/ˈevɪdənt/',
    meanings: [
      { pos: 'adjective', en: 'Clearly seen or understood; obvious.', th: 'ชัดเจน, เห็นได้ชัด' },
    ],
    antonyms: ['unclear', 'hidden'],
    examples: [
      'It was evident from her tone that she was not pleased with the outcome.',
      'The improvement in his performance was evident to everyone on the team.',
      'The damage caused by the storm was evident throughout the entire neighbourhood.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'expand',
    level: 'B1',
    partOfSpeech: ['verb [I]', 'verb [T]'],
    ipa_uk: '/ɪkˈspænd/',
    ipa_us: '/ɪkˈspænd/',
    meanings: [
      { pos: 'verb [I/T]', en: 'To become larger in size, number, or amount, or to make something larger.', th: 'ขยาย, เพิ่มขึ้น, ขยายตัว' },
    ],
    antonyms: ['shrink', 'reduce'],
    examples: [
      'The company plans to expand into new international markets next year.',
      'Reading regularly helps expand your vocabulary over time.',
      'The balloon expanded rapidly as more air was pumped inside.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'experience',
    level: 'B1',
    partOfSpeech: ['noun [C]', 'noun [U]', 'verb [T]'],
    ipa_uk: '/ɪkˈspɪəriəns/',
    ipa_us: '/ɪkˈspɪriəns/',
    meanings: [
      { pos: 'noun [U]', en: 'Knowledge or skill gained from doing something over a period of time.', th: 'ประสบการณ์, ความชำนาญ' },
      { pos: 'noun [C]', en: 'Something that happens to you and affects how you feel.', th: 'ประสบการณ์, เหตุการณ์ที่ผ่านมา' },
      { pos: 'verb [T]', en: 'To have something happen to you or feel something.', th: 'ประสบ, พบเจอ, รู้สึก' },
    ],
    antonyms: ['inexperience', 'ignorance'],
    examples: [
      'She has over ten years of experience working in international finance.',
      'Travelling alone was a life-changing experience for him.',
      'Many people experience anxiety before an important job interview.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'flexible',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/ˈfleksɪbəl/',
    ipa_us: '/ˈfleksɪbəl/',
    meanings: [
      { pos: 'adjective', en: 'Able to change easily according to different situations or requirements.', th: 'ยืดหยุ่น, ปรับได้' },
      { pos: 'adjective', en: 'Able to bend easily without breaking.', th: 'งอได้, โค้งได้' },
    ],
    antonyms: ['rigid', 'inflexible'],
    examples: [
      'The new working arrangement offers employees a more flexible schedule.',
      'You need to be flexible when travelling, as plans can change quickly.',
      'This flexible material can be bent into almost any shape without breaking.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'focus',
    level: 'B1',
    partOfSpeech: ['verb [I]', 'verb [T]', 'noun [U]', 'noun [C]'],
    ipa_uk: '/ˈfəʊkəs/',
    ipa_us: '/ˈfoʊkəs/',
    meanings: [
      { pos: 'verb [I/T]', en: 'To give all your attention to something or to make something clearer.', th: 'มุ่งเน้น, จดจ่อ, โฟกัส' },
      { pos: 'noun [U]', en: 'The main subject of attention or interest.', th: 'จุดสนใจ, ความสนใจหลัก' },
    ],
    antonyms: ['distract', 'ignore'],
    examples: [
      'Try to focus on one task at a time rather than doing everything at once.',
      'The focus of the meeting was on improving customer satisfaction.',
      'She focused the camera carefully before taking the photograph.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'fundamental',
    level: 'B1',
    partOfSpeech: ['adjective', 'noun [C]'],
    ipa_uk: '/ˌfʌndəˈmentəl/',
    ipa_us: '/ˌfʌndəˈmentəl/',
    meanings: [
      { pos: 'adjective', en: 'Forming the most basic and important part of something.', th: 'พื้นฐาน, สำคัญอย่างยิ่ง' },
      { pos: 'noun [C]', en: 'A basic rule or principle that something is based on.', th: 'หลักพื้นฐาน, สิ่งสำคัญที่สุด' },
    ],
    antonyms: ['minor', 'secondary'],
    examples: [
      'Trust is fundamental to any strong and lasting relationship.',
      'The fundamentals of good writing include clarity and structure.',
      'There is a fundamental difference between the two approaches to the problem.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'generate',
    level: 'B1',
    partOfSpeech: ['verb [T]'],
    ipa_uk: '/ˈdʒenəreɪt/',
    ipa_us: '/ˈdʒenəreɪt/',
    meanings: [
      { pos: 'verb [T]', en: 'To produce or create something, such as energy, money, or ideas.', th: 'สร้าง, ก่อให้เกิด, ผลิต' },
    ],
    antonyms: ['destroy', 'consume'],
    examples: [
      'The new factory will generate hundreds of jobs for the local community.',
      'Solar panels generate electricity from sunlight without producing pollution.',
      'The controversial decision generated a great deal of public debate.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'genuine',
    level: 'B1',
    partOfSpeech: ['adjective'],
    ipa_uk: '/ˈdʒenjuɪn/',
    ipa_us: '/ˈdʒenjuɪn/',
    meanings: [
      { pos: 'adjective', en: 'Real and exactly what it appears to be; not false or copied.', th: 'แท้จริง, ของแท้' },
      { pos: 'adjective', en: 'Honest and sincere in feelings or intentions.', th: 'จริงใจ, ซื่อสัตย์' },
    ],
    antonyms: ['fake', 'artificial'],
    examples: [
      'The museum confirmed that the painting was a genuine work by the artist.',
      'She showed genuine concern for the wellbeing of her students.',
      'He gave a genuine smile rather than a polite but empty one.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
  {
    word: 'guarantee',
    level: 'B1',
    partOfSpeech: ['verb [T]', 'noun [C]'],
    ipa_uk: '/ˌɡærənˈtiː/',
    ipa_us: '/ˌɡærənˈtiː/',
    meanings: [
      { pos: 'verb [T]', en: 'To promise that something will definitely happen or be done.', th: 'รับประกัน, การันตี' },
      { pos: 'noun [C]', en: 'A firm promise that something will happen or that a product will work correctly.', th: 'การรับประกัน, สัญญา' },
    ],
    antonyms: ['doubt', 'uncertainty'],
    examples: [
      'I cannot guarantee that the package will arrive before the weekend.',
      'The product comes with a two-year guarantee against any manufacturing defects.',
      'Hard work does not always guarantee success, but it certainly improves your chances.',
    ],
    box: 1, correct: 0, seen: 0, lastSeen: null,
  },
];

// ===== DISTRACTORS MAP =====
const DISTRACTORS = {
  'achieve':      ['ล้มเหลว','ละทิ้ง','รอคอย','หลีกเลี่ยง'],
  'negotiate':    ['สั่งการ','หลีกเลี่ยง','ตัดสิน','บังคับ'],
  'contribute':   ['ขัดขวาง','ปฏิเสธ','แข่งขัน','เพิกเฉย'],
  'emphasize':    ['ลดความสำคัญ','ซ่อนเร้น','เปรียบเทียบ','คัดค้าน'],
  'persist':      ['ยอมแพ้','หยุดพัก','เปลี่ยนใจ','ล้มเลิก'],
  'analyze':      ['เดาสุ่ม','ละเลย','รวบรวม','คาดเดา'],
  'interpret':    ['เพิกเฉย','บิดเบือน','คำนวณ','สับสน'],
  'consequence':  ['สาเหตุ','โอกาส','ความตั้งใจ','วิธีการ'],
  'significant':  ['ไม่สำคัญ','ชัดเจน','เล็กน้อย','ลึกลับ'],
  'establish':    ['ทำลาย','ยกเลิก','ลังเล','ระงับ'],
  'assumption':   ['ข้อเท็จจริง','คำพิพากษา','การพิสูจน์','ผลลัพธ์'],
  'circumstance': ['ความบังเอิญ','แผนการ','ผลที่ตามมา','ความตั้งใจ'],
  'consistent':   ['ไม่แน่นอน','ตรงกันข้าม','สับสน','เปลี่ยนแปลง'],
  'demonstrate':  ['ซ่อนเร้น','เดาสุ่ม','ปฏิเสธ','ยอมรับ'],
  'evaluate':     ['เพิกเฉย','เดาสุ่ม','คาดเดา','หลีกเลี่ยง'],
  'flexible':     ['แข็งกร้าว','ตายตัว','ไม่แน่ใจ','ล้มเหลว'],
  'generate':     ['ทำลาย','ลดลง','ป้องกัน','ระงับ'],
  'indicate':     ['ซ่อนเร้น','คัดค้าน','เพิกเฉย','หลีกเลี่ยง'],
  'justify':      ['คัดค้าน','ปฏิเสธ','โต้แย้ง','ขัดขวาง'],
  'maintain':     ['ละทิ้ง','ทำลาย','เพิกเฉย','ลดลง'],
  'obtain':       ['สูญเสีย','ยอมแพ้','ปฏิเสธ','ละทิ้ง'],
  'potential':    ['ข้อจำกัด','ความล้มเหลว','ปัญหา','อุปสรรค'],
  'relevant':     ['ไม่เกี่ยวข้อง','สับสน','คลุมเครือ','ไม่ชัดเจน'],
  'sufficient':   ['ไม่เพียงพอ','มากเกินไป','น้อยเกินไป','ขาดแคลน'],
  'tendency':     ['ข้อยกเว้น','ความบังเอิญ','ผลลัพธ์','สาเหตุ'],
  'apparent':     ['ซ่อนเร้น','คลุมเครือ','ลึกลับ','ไม่ชัดเจน'],
  'despite':      ['เพราะว่า','เนื่องจาก','ดังนั้น','ในขณะที่'],
  'whereas':      ['เพราะว่า','ดังนั้น','นอกจากนี้','ยิ่งไปกว่านั้น'],
  'approximate':  ['แน่นอน','เกินจริง','ผิดพลาด','สมบูรณ์'],
  'diverse':      ['เหมือนกัน','เดียว','สม่ำเสมอ','แน่นอน'],
  'essential':    ['ไม่จำเป็น','ไม่สำคัญ','ไม่เกี่ยวข้อง','ทางเลือก'],
  'fundamental':  ['ผิวเผิน','ไม่สำคัญ','รอง','ชั่วคราว'],
  'guarantee':    ['ปฏิเสธ','สงสัย','คาดเดา','ทดสอบ'],
  'influence':    ['ไม่เกี่ยวข้อง','ป้องกัน','ขัดขวาง','ต่อต้าน'],
  'perception':   ['ความจริง','ข้อเท็จจริง','ผลลัพธ์','การพิสูจน์'],
  'resolve':      ['ปล่อยทิ้ง','หลีกเลี่ยง','ซับซ้อน','เพิกเฉย'],
  'strategy':     ['ความบังเอิญ','ผลลัพธ์','ปัญหา','ความสับสน'],
  'transition':   ['ความหยุดนิ่ง','ความคงที่','การยืนกราน','การปฏิเสธ'],
  'voluntary':    ['บังคับ','จำเป็น','ฝืนใจ','บีบบังคับ'],
  'widespread':   ['หายาก','จำกัด','เฉพาะที่','น้อยมาก'],
};

// ===== QUIZ QUESTIONS (grammar fill-in) =====
const GRAMMAR_QUESTIONS = [
  {
    word:'achieve', ipa:'/əˈtʃiːv/', topic:'Past Simple',
    sentence:'She ___ her goal after years of hard work.',
    options:['achieved','achieves','has achieved','was achieving'],
    answer:'achieved',
    explanation:'ใช้ Past Simple (V2) เพราะ "after years of hard work" บ่งบอกว่าเหตุการณ์นี้จบสมบูรณ์แล้วในอดีต',
  },
  {
    word:'negotiate', ipa:'/nɪˈɡəʊʃieɪt/', topic:'Present Perfect',
    sentence:'The two companies ___ a new agreement since last year.',
    options:['have negotiated','negotiated','are negotiating','will negotiate'],
    answer:'have negotiated',
    explanation:'ใช้ Present Perfect เพราะ "since last year" เชื่อมอดีตกับปัจจุบัน การเจรจายังมีผลถึงตอนนี้',
  },
  {
    word:'contribute', ipa:'/kənˈtrɪbjuːt/', topic:'Passive Voice',
    sentence:'Many useful ideas ___ by the students during the meeting.',
    options:['were contributed','contributed','have contributed','are contributing'],
    answer:'were contributed',
    explanation:'ใช้ Passive Voice (were + V3) เพราะ "ideas" คือสิ่งที่ถูกกระทำ ไม่ใช่ผู้กระทำ',
  },
  {
    word:'persist', ipa:'/pəˈsɪst/', topic:'Conditionals',
    sentence:'If she ___ with her training, she would become a champion.',
    options:['persisted','persists','had persisted','would persist'],
    answer:'persisted',
    explanation:'Second Conditional ใช้ V2 ใน if-clause เพื่อแสดงสถานการณ์สมมติที่ไม่น่าเป็นจริงในปัจจุบัน',
  },
  {
    word:'maintain', ipa:'/meɪnˈteɪn/', topic:'Modal Verbs',
    sentence:'You ___ a consistent study routine if you want to improve.',
    options:['should maintain','maintained','are maintaining','have maintained'],
    answer:'should maintain',
    explanation:'ใช้ Modal Verb "should" + V1 เพื่อแสดงคำแนะนำ โครงสร้างคือ Subject + modal + V1',
  },
  {
    word:'establish', ipa:'/ɪˈstæblɪʃ/', topic:'Past Simple',
    sentence:'The university ___ its first international programme in 1998.',
    options:['established','establishes','has established','was establishing'],
    answer:'established',
    explanation:'ใช้ Past Simple เพราะมีการระบุเวลาในอดีตชัดเจน "in 1998"',
  },
  {
    word:'analyze', ipa:'/ˈænəlaɪz/', topic:'Present Perfect',
    sentence:'The researchers ___ the data three times already.',
    options:['have analyzed','analyzed','are analyzing','will analyze'],
    answer:'have analyzed',
    explanation:'ใช้ Present Perfect เพราะ "already" บ่งบอกว่าทำเสร็จแล้วก่อนเวลาปัจจุบันและยังเกี่ยวข้องกับตอนนี้',
  },
  {
    word:'evaluate', ipa:'/ɪˈvæljueɪt/', topic:'Passive Voice',
    sentence:'The proposals ___ by the committee last Friday.',
    options:['were evaluated','evaluated','have been evaluated','are evaluating'],
    answer:'were evaluated',
    explanation:'ใช้ Passive Voice Past Simple เพราะ "committee" เป็นผู้กระทำ แต่ไม่ใช่ประธาน และมีบอกเวลา "last Friday"',
  },
];
