// ===== APP STATE =====
const STATE = {
  level: 'B1',
  dailyGoal: 20,
  darkMode: false,
  streak: 7,
  totalDays: 23,
  boxes: { 1:18, 2:24, 3:31, 4:22, 5:16, 6:9 },
  grammarStats: {
    'Past Simple':       { attempts:31, correct:25 },
    'Present Perfect':   { attempts:22, correct:10 },
    'Passive Voice':     { attempts:18, correct: 9 },
    'Conditionals':      { attempts:15, correct: 9 },
    'Modal Verbs':       { attempts: 9, correct: 6 },
  },
  todayNew: 12,
  todayReview: 8,
  todayGrammar: 5,
  todayAccuracy: 84,
  velocity7: [8,15,20,12,18,22,12],
  accuracy30: {
    vocab:   [58,60,62,59,63,65,64,67,66,68,70,69,71,72,70,73,74,72,75,76,75,77,76,78,77,79,78,80,79,78],
    grammar: [42,44,43,46,45,47,48,46,49,50,49,51,50,52,53,51,54,53,55,56,54,57,56,58,57,59,60,61,62,65],
    reading: [50,52,51,54,53,55,56,54,57,58,57,59,60,61,59,62,63,61,64,65,63,66,67,65,68,69,67,70,71,72],
  },
};

// ===== GRAMMAR DATABASE =====
const GRAMMAR_DB = {
  'Past Simple': {
    use: 'เหตุการณ์ที่เกิดขึ้นและจบแล้วในอดีต มักมีคำบอกเวลาเช่น yesterday, last year, ago',
    structure: 'Subject + V2 (past form)',
    negative: 'Subject + did not + V1',
    question: 'Did + Subject + V1?',
    examples: [
      'She achieved her goal last year.',
      'They negotiated a deal in 2022.',
      'He did not contribute to the project.',
    ],
  },
  'Present Perfect': {
    use: 'เหตุการณ์ที่เกิดในอดีตแต่ยังเชื่อมกับปัจจุบัน หรือประสบการณ์ มักมี since, for, already, yet',
    structure: 'Subject + have / has + V3',
    negative: 'Subject + have/has + not + V3',
    question: 'Have / Has + Subject + V3?',
    examples: [
      'She has achieved a lot in her career.',
      'They have negotiated successfully since 2020.',
      'He has not contributed any ideas yet.',
    ],
  },
  'Passive Voice': {
    use: 'เน้นผลลัพธ์หรือสิ่งที่ถูกกระทำ ไม่เน้นผู้กระทำ ใช้บ่อยในงานเขียนวิชาการและข่าว',
    structure: 'Subject + was / were + V3',
    negative: 'Subject + was/were + not + V3',
    question: 'Was / Were + Subject + V3?',
    examples: [
      'The goal was achieved by the entire team.',
      'A new deal was negotiated last month.',
      'Many ideas were contributed by the students.',
    ],
  },
  'Conditionals': {
    use: 'Second Conditional — สถานการณ์สมมติที่ไม่น่าเป็นจริงในปัจจุบันหรืออนาคต',
    structure: 'If + Subject + V2,  Subject + would + V1',
    negative: 'If + Subject + did not + V1,  Subject + would not + V1',
    question: 'What would happen if...?',
    examples: [
      'If she persisted, she would achieve her goal.',
      'If they negotiated better, they would win.',
      'If he contributed more, the team would improve.',
    ],
  },
  'Modal Verbs': {
    use: 'แสดงความสามารถ ความเป็นไปได้ คำแนะนำ หรือความจำเป็น',
    structure: 'Subject + modal + V1  (modal = can/could/should/must/might/may)',
    negative: 'Subject + modal + not + V1',
    question: 'Modal + Subject + V1?',
    examples: [
      'You should emphasize the key points.',
      'She can achieve anything with effort.',
      'They might negotiate a better deal.',
    ],
  },
  'Future Simple': {
    use: 'การกระทำหรือเหตุการณ์ในอนาคต การตัดสินใจทันที หรือการคาดการณ์',
    structure: 'Subject + will + V1',
    negative: 'Subject + will not (won\'t) + V1',
    question: 'Will + Subject + V1?',
    examples: [
      'She will achieve her target next month.',
      'They will negotiate the terms tomorrow.',
      'He will not contribute if he is busy.',
    ],
  },
  'Present Continuous': {
    use: 'การกระทำที่กำลังเกิดขึ้นตอนนี้ หรือแผนในอนาคตที่แน่นอน',
    structure: 'Subject + am/is/are + V-ing',
    negative: 'Subject + am/is/are + not + V-ing',
    question: 'Am/Is/Are + Subject + V-ing?',
    examples: [
      'She is currently analyzing the data.',
      'They are negotiating a new agreement.',
      'He is not contributing to the discussion.',
    ],
  },
};

// ===== VOCABULARY DATABASE (B1 core — 40 words) =====
// Full version will load from Oxford 3000 JSON
const WORDS = [
  {
    word:'achieve', ipa:'/əˈtʃiːv/', level:'B1',
    thai:'บรรลุ, ทำสำเร็จ',
    def:'To successfully reach a goal or complete something through effort.',
    examples:[
      'She achieved her dream of becoming a doctor.',
      'He worked hard to achieve success in his career.',
      'They achieved excellent results in the final exam.',
    ],
    box:1, correct:3, seen:7, lastSeen: Date.now()-86400000,
  },
  {
    word:'negotiate', ipa:'/nɪˈɡəʊʃieɪt/', level:'B1',
    thai:'เจรจา, ต่อรอง',
    def:'To discuss something with others in order to reach an agreement.',
    examples:[
      'They negotiated a new contract with the supplier.',
      'She negotiated a lower price for the apartment.',
      'Both sides agreed to negotiate a peaceful solution.',
    ],
    box:2, correct:4, seen:8, lastSeen: Date.now()-172800000,
  },
  {
    word:'contribute', ipa:'/kənˈtrɪbjuːt/', level:'B1',
    thai:'มีส่วนร่วม, ช่วยเหลือ, บริจาค',
    def:'To give something such as time, money, or ideas to help achieve a result.',
    examples:[
      'Everyone should contribute to the team project.',
      'She contributed many creative ideas to the meeting.',
      'His research contributed greatly to modern science.',
    ],
    box:2, correct:5, seen:9, lastSeen: Date.now()-86400000,
  },
  {
    word:'emphasize', ipa:'/ˈemfəsaɪz/', level:'B1',
    thai:'เน้น, ย้ำ, ให้ความสำคัญ',
    def:'To give special importance or attention to something.',
    examples:[
      'The teacher emphasized the importance of daily practice.',
      'He emphasized that safety must always come first.',
      'She emphasized her main points clearly in the report.',
    ],
    box:3, correct:7, seen:11, lastSeen: Date.now()-43200000,
  },
  {
    word:'persist', ipa:'/pəˈsɪst/', level:'B1',
    thai:'ยืนกราน, อดทนต่อเนื่อง, ดำเนินต่อไป',
    def:'To continue doing something despite difficulty or opposition.',
    examples:[
      'She persisted with her studies despite many challenges.',
      'If you persist, you will eventually succeed.',
      'He persisted in asking questions until he understood.',
    ],
    box:1, correct:1, seen:4, lastSeen: Date.now()-259200000,
  },
  {
    word:'analyze', ipa:'/ˈænəlaɪz/', level:'B1',
    thai:'วิเคราะห์, ตรวจสอบ',
    def:'To examine something carefully in order to understand it.',
    examples:[
      'Scientists analyze data to find patterns.',
      'She analyzed the problem carefully before acting.',
      'We need to analyze the results of the survey.',
    ],
    box:3, correct:8, seen:12, lastSeen: Date.now()-21600000,
  },
  {
    word:'interpret', ipa:'/ɪnˈtɜːprɪt/', level:'B1',
    thai:'ตีความ, แปลความหมาย',
    def:'To explain or decide what something means.',
    examples:[
      'How do you interpret this sentence?',
      'The judge interpreted the law very strictly.',
      'She interpreted his silence as a sign of agreement.',
    ],
    box:2, correct:4, seen:8, lastSeen: Date.now()-172800000,
  },
  {
    word:'consequence', ipa:'/ˈkɒnsɪkwəns/', level:'B1',
    thai:'ผลที่ตามมา, ผลลัพธ์',
    def:'A result or effect of an action or condition.',
    examples:[
      'The consequence of not studying is poor results.',
      'He had to face the consequences of his actions.',
      'Every decision has a consequence.',
    ],
    box:4, correct:9, seen:11, lastSeen: Date.now()-3600000,
  },
  {
    word:'significant', ipa:'/sɪɡˈnɪfɪkənt/', level:'B1',
    thai:'สำคัญ, มีนัยสำคัญ',
    def:'Large or important enough to have a noticeable effect.',
    examples:[
      'There was a significant improvement in her grades.',
      'This is a significant discovery for modern medicine.',
      'The change had a significant impact on the economy.',
    ],
    box:4, correct:10, seen:12, lastSeen: Date.now()-7200000,
  },
  {
    word:'establish', ipa:'/ɪˈstæblɪʃ/', level:'B1',
    thai:'ก่อตั้ง, สร้าง, พิสูจน์',
    def:'To set up or create something permanent, or to prove something.',
    examples:[
      'They established a new company in 2020.',
      'The school was established over one hundred years ago.',
      'She established herself as a leading expert in the field.',
    ],
    box:5, correct:14, seen:16, lastSeen: Date.now()-3600000,
  },
  {
    word:'assumption', ipa:'/əˈsʌmpʃən/', level:'B1',
    thai:'การสันนิษฐาน, ข้อสมมติ',
    def:'Something that you accept as true without proof.',
    examples:[
      'Do not make assumptions without checking the facts.',
      'His plan was based on a false assumption.',
      'She questioned every assumption in the report.',
    ],
    box:2, correct:3, seen:7, lastSeen: Date.now()-86400000,
  },
  {
    word:'circumstance', ipa:'/ˈsɜːkəmstæns/', level:'B1',
    thai:'สถานการณ์, เหตุการณ์แวดล้อม',
    def:'A fact or condition that affects a situation.',
    examples:[
      'Under normal circumstances, the shop opens at nine.',
      'The circumstances of the accident are still unclear.',
      'She succeeded despite difficult circumstances.',
    ],
    box:3, correct:6, seen:9, lastSeen: Date.now()-43200000,
  },
  {
    word:'consistent', ipa:'/kənˈsɪstənt/', level:'B1',
    thai:'สม่ำเสมอ, สอดคล้องกัน',
    def:'Always behaving in the same way or having the same quality.',
    examples:[
      'You need to be consistent in your daily practice.',
      'Her performance has been consistent throughout the year.',
      'The results were consistent with our predictions.',
    ],
    box:4, correct:8, seen:10, lastSeen: Date.now()-7200000,
  },
  {
    word:'demonstrate', ipa:'/ˈdemənstreɪt/', level:'B1',
    thai:'แสดงให้เห็น, พิสูจน์',
    def:'To show clearly that something exists or is true.',
    examples:[
      'She demonstrated how to use the new software.',
      'The experiment demonstrated that the theory was correct.',
      'He demonstrated great courage during the crisis.',
    ],
    box:3, correct:5, seen:8, lastSeen: Date.now()-86400000,
  },
  {
    word:'evaluate', ipa:'/ɪˈvæljueɪt/', level:'B1',
    thai:'ประเมิน, ตีค่า',
    def:'To judge or calculate the quality or value of something.',
    examples:[
      'Teachers evaluate students through tests and projects.',
      'We need to evaluate the risks before deciding.',
      'She evaluated the evidence carefully.',
    ],
    box:2, correct:3, seen:6, lastSeen: Date.now()-172800000,
  },
  {
    word:'flexible', ipa:'/ˈfleksɪbəl/', level:'B1',
    thai:'ยืดหยุ่น, ปรับได้',
    def:'Able to change or be changed easily according to the situation.',
    examples:[
      'A good plan should be flexible enough to adapt.',
      'She has a flexible working schedule.',
      'You need to be flexible when travelling.',
    ],
    box:5, correct:11, seen:13, lastSeen: Date.now()-3600000,
  },
  {
    word:'generate', ipa:'/ˈdʒenəreɪt/', level:'B1',
    thai:'สร้าง, ก่อให้เกิด',
    def:'To produce or create something.',
    examples:[
      'The project generated a lot of interest.',
      'Solar panels generate electricity from sunlight.',
      'His speech generated much debate.',
    ],
    box:3, correct:6, seen:9, lastSeen: Date.now()-43200000,
  },
  {
    word:'indicate', ipa:'/ˈɪndɪkeɪt/', level:'B1',
    thai:'บ่งชี้, แสดงให้เห็น',
    def:'To show or point to something.',
    examples:[
      'The results indicate a clear trend.',
      'She indicated that she was ready to begin.',
      'The sign indicated the direction of the exit.',
    ],
    box:4, correct:7, seen:9, lastSeen: Date.now()-7200000,
  },
  {
    word:'justify', ipa:'/ˈdʒʌstɪfaɪ/', level:'B1',
    thai:'พิสูจน์ความถูกต้อง, ให้เหตุผล',
    def:'To show that something is right or reasonable.',
    examples:[
      'Can you justify your decision to the committee?',
      'The outcome justified all the hard work.',
      'He tried to justify his behaviour but failed.',
    ],
    box:2, correct:2, seen:5, lastSeen: Date.now()-259200000,
  },
  {
    word:'maintain', ipa:'/meɪnˈteɪn/', level:'B1',
    thai:'รักษา, ดูแล, ยืนยัน',
    def:'To keep something in good condition or at the same level.',
    examples:[
      'It is important to maintain a healthy lifestyle.',
      'She maintained her focus throughout the exam.',
      'The company maintained high standards of quality.',
    ],
    box:4, correct:9, seen:11, lastSeen: Date.now()-3600000,
  },
  {
    word:'obtain', ipa:'/əbˈteɪn/', level:'B1',
    thai:'ได้รับ, ได้มา',
    def:'To get something, especially by making an effort.',
    examples:[
      'She obtained a scholarship to study abroad.',
      'You can obtain the form from the office.',
      'He obtained permission before entering.',
    ],
    box:3, correct:5, seen:8, lastSeen: Date.now()-86400000,
  },
  {
    word:'potential', ipa:'/pəˈtenʃəl/', level:'B1',
    thai:'ศักยภาพ, ที่เป็นไปได้',
    def:'The ability to develop or achieve something in the future.',
    examples:[
      'She has the potential to become a great leader.',
      'The project has enormous potential.',
      'They identified potential risks early on.',
    ],
    box:5, correct:12, seen:14, lastSeen: Date.now()-3600000,
  },
  {
    word:'relevant', ipa:'/ˈreləvənt/', level:'B1',
    thai:'เกี่ยวข้อง, สำคัญในบริบทนั้น',
    def:'Directly connected with and important to what is being discussed.',
    examples:[
      'Please include only relevant information.',
      'Her experience is highly relevant to the job.',
      'Is this point relevant to our discussion?',
    ],
    box:3, correct:6, seen:9, lastSeen: Date.now()-43200000,
  },
  {
    word:'sufficient', ipa:'/səˈfɪʃənt/', level:'B1',
    thai:'เพียงพอ',
    def:'Enough for a particular purpose.',
    examples:[
      'Is there sufficient evidence to support the claim?',
      'She did not have sufficient time to finish.',
      'A small amount is sufficient for this recipe.',
    ],
    box:2, correct:3, seen:6, lastSeen: Date.now()-172800000,
  },
  {
    word:'tendency', ipa:'/ˈtendənsi/', level:'B1',
    thai:'แนวโน้ม, ความโน้มเอียง',
    def:'A likelihood of behaving in a particular way.',
    examples:[
      'She has a tendency to arrive late.',
      'There is a tendency for prices to rise in winter.',
      'He noticed a tendency toward overconfidence.',
    ],
    box:2, correct:2, seen:5, lastSeen: Date.now()-259200000,
  },
  {
    word:'apparent', ipa:'/əˈpærənt/', level:'B1',
    thai:'ชัดเจน, เห็นได้ชัด',
    def:'Easy to see or understand; obvious.',
    examples:[
      'It was apparent that she was nervous.',
      'The apparent cause of the problem was lack of sleep.',
      'His talent became apparent at an early age.',
    ],
    box:3, correct:5, seen:8, lastSeen: Date.now()-86400000,
  },
  {
    word:'despite', ipa:'/dɪˈspaɪt/', level:'B1',
    thai:'ทั้งๆที่, แม้ว่า',
    def:'Used to show that something happened even though something else might have prevented it.',
    examples:[
      'She passed the exam despite being ill.',
      'Despite the rain, they continued the match.',
      'He succeeded despite having no formal training.',
    ],
    box:4, correct:8, seen:10, lastSeen: Date.now()-7200000,
  },
  {
    word:'whereas', ipa:'/weərˈæz/', level:'B1',
    thai:'ในขณะที่, แต่ว่า',
    def:'Used to compare two things that are different.',
    examples:[
      'She prefers tea, whereas he drinks coffee.',
      'Whereas some enjoy risk, others prefer safety.',
      'The north is cold, whereas the south is warm.',
    ],
    box:2, correct:3, seen:6, lastSeen: Date.now()-172800000,
  },
  {
    word:'approximate', ipa:'/əˈprɒksɪmət/', level:'B1',
    thai:'โดยประมาณ, ใกล้เคียง',
    def:'Close to the exact amount but not completely accurate.',
    examples:[
      'The approximate cost is five hundred dollars.',
      'Can you give me an approximate time of arrival?',
      'The approximate distance is fifty kilometres.',
    ],
    box:3, correct:4, seen:7, lastSeen: Date.now()-43200000,
  },
  {
    word:'diverse', ipa:'/daɪˈvɜːs/', level:'B1',
    thai:'หลากหลาย, แตกต่าง',
    def:'Showing a great deal of variety.',
    examples:[
      'The city has a diverse population.',
      'She has diverse interests, from art to science.',
      'A diverse team produces more creative solutions.',
    ],
    box:5, correct:10, seen:12, lastSeen: Date.now()-3600000,
  },
  {
    word:'essential', ipa:'/ɪˈsenʃəl/', level:'B1',
    thai:'จำเป็น, สำคัญมาก',
    def:'Completely necessary; extremely important.',
    examples:[
      'Water is essential for all living things.',
      'It is essential that you arrive on time.',
      'She packed only the essential items.',
    ],
    box:5, correct:13, seen:15, lastSeen: Date.now()-3600000,
  },
  {
    word:'fundamental', ipa:'/ˌfʌndəˈmentəl/', level:'B1',
    thai:'พื้นฐาน, สำคัญอย่างยิ่ง',
    def:'Forming the base or most important part of something.',
    examples:[
      'Trust is fundamental to any relationship.',
      'She learned the fundamental rules of grammar.',
      'Access to clean water is a fundamental human right.',
    ],
    box:4, correct:7, seen:9, lastSeen: Date.now()-7200000,
  },
  {
    word:'guarantee', ipa:'/ˌɡærənˈtiː/', level:'B1',
    thai:'รับรอง, ค้ำประกัน',
    def:'To promise that something will definitely happen.',
    examples:[
      'I cannot guarantee that the plan will work.',
      'The product comes with a two-year guarantee.',
      'Hard work does not guarantee success, but it helps.',
    ],
    box:3, correct:5, seen:8, lastSeen: Date.now()-86400000,
  },
  {
    word:'influence', ipa:'/ˈɪnfluəns/', level:'B1',
    thai:'อิทธิพล, ส่งผลต่อ',
    def:'The power to affect the way someone thinks or behaves.',
    examples:[
      'Music has a strong influence on mood.',
      'Her mentor influenced her career greatly.',
      'Social media influences how people see the world.',
    ],
    box:4, correct:9, seen:11, lastSeen: Date.now()-3600000,
  },
  {
    word:'perception', ipa:'/pəˈsepʃən/', level:'B1',
    thai:'การรับรู้, ความเข้าใจ',
    def:'The way you notice or understand something using your senses or mind.',
    examples:[
      'Public perception of the brand changed after the scandal.',
      'Her perception of the problem was very clear.',
      'Perception can differ greatly from reality.',
    ],
    box:2, correct:2, seen:5, lastSeen: Date.now()-259200000,
  },
  {
    word:'resolve', ipa:'/rɪˈzɒlv/', level:'B1',
    thai:'แก้ไข, ตัดสินใจ, มุ่งมั่น',
    def:'To find a solution to a problem or argument.',
    examples:[
      'They resolved their differences through discussion.',
      'She resolved to work harder after the setback.',
      'The dispute was resolved without going to court.',
    ],
    box:3, correct:6, seen:9, lastSeen: Date.now()-43200000,
  },
  {
    word:'strategy', ipa:'/ˈstrætədʒi/', level:'B1',
    thai:'กลยุทธ์, แผนการ',
    def:'A plan designed to achieve a long-term goal.',
    examples:[
      'The company developed a new marketing strategy.',
      'What is your strategy for passing the exam?',
      'A good strategy requires careful planning.',
    ],
    box:5, correct:11, seen:13, lastSeen: Date.now()-3600000,
  },
  {
    word:'transition', ipa:'/trænˈzɪʃən/', level:'B1',
    thai:'การเปลี่ยนผ่าน, การเปลี่ยนแปลง',
    def:'The process of changing from one state or condition to another.',
    examples:[
      'The transition from school to university can be challenging.',
      'The country is in a period of political transition.',
      'She managed the transition smoothly.',
    ],
    box:2, correct:3, seen:6, lastSeen: Date.now()-172800000,
  },
  {
    word:'voluntary', ipa:'/ˈvɒləntri/', level:'B1',
    thai:'โดยสมัครใจ, อาสาสมัคร',
    def:'Done, given, or acting by free choice, without being forced.',
    examples:[
      'Participation in the survey is voluntary.',
      'She does voluntary work at the local hospital.',
      'He made a voluntary decision to resign.',
    ],
    box:3, correct:4, seen:7, lastSeen: Date.now()-86400000,
  },
  {
    word:'widespread', ipa:'/ˈwaɪdspred/', level:'B1',
    thai:'แพร่หลาย, กว้างขวาง',
    def:'Found or distributed over a large area or number of people.',
    examples:[
      'There is widespread support for the new policy.',
      'The disease became widespread within weeks.',
      'Smartphones are now widespread around the world.',
    ],
    box:4, correct:8, seen:10, lastSeen: Date.now()-7200000,
  },
];

// ===== DISTRACTORS MAP =====
const DISTRACTORS = {
  'achieve':      ['ล้มเหลว','ละทิ้ง','รอคอย','หลีกเลี่ยง'],
  'negotiate':    ['สั่งการ','หลีกเลี่ยง','ตัดสิน','บังคับ'],
  'contribute':   ['ขัดขวาง','ปฏิเสธ','แข่งขัน','เพิกเฉย'],
  'emphasize':    ['ลดความสำคัญ','ซ่อนเร้น','เปรียบเทียบ','คัดค้าน'],
  'persist':      ['ยอมแพ้','หยุดพัก','เปลี่ยนใจ','ล้มเลิก'],
  'analyze':      ['เดาสุ่ม','ละเลย','รวบรวม','คาดเดา'],
  'interpret':    ['เพิกเฉย','บิดเบือน','คำนวณ','สับสน'],
  'consequence':  ['สาเหตุ','โอกาส','ความตั้งใจ','วิธีการ'],
  'significant':  ['ไม่สำคัญ','ชัดเจน','เล็กน้อย','ลึกลับ'],
  'establish':    ['ทำลาย','ยกเลิก','ลังเล','ระงับ'],
  'assumption':   ['ข้อเท็จจริง','คำพิพากษา','การพิสูจน์','ผลลัพธ์'],
  'circumstance': ['ความบังเอิญ','แผนการ','ผลที่ตามมา','ความตั้งใจ'],
  'consistent':   ['ไม่แน่นอน','ตรงกันข้าม','สับสน','เปลี่ยนแปลง'],
  'demonstrate':  ['ซ่อนเร้น','เดาสุ่ม','ปฏิเสธ','ยอมรับ'],
  'evaluate':     ['เพิกเฉย','เดาสุ่ม','คาดเดา','หลีกเลี่ยง'],
  'flexible':     ['แข็งกร้าว','ตายตัว','ไม่แน่ใจ','ล้มเหลว'],
  'generate':     ['ทำลาย','ลดลง','ป้องกัน','ระงับ'],
  'indicate':     ['ซ่อนเร้น','คัดค้าน','เพิกเฉย','หลีกเลี่ยง'],
  'justify':      ['คัดค้าน','ปฏิเสธ','โต้แย้ง','ขัดขวาง'],
  'maintain':     ['ละทิ้ง','ทำลาย','เพิกเฉย','ลดลง'],
  'obtain':       ['สูญเสีย','ยอมแพ้','ปฏิเสธ','ละทิ้ง'],
  'potential':    ['ข้อจำกัด','ความล้มเหลว','ปัญหา','อุปสรรค'],
  'relevant':     ['ไม่เกี่ยวข้อง','สับสน','คลุมเครือ','ไม่ชัดเจน'],
  'sufficient':   ['ไม่เพียงพอ','มากเกินไป','น้อยเกินไป','ขาดแคลน'],
  'tendency':     ['ข้อยกเว้น','ความบังเอิญ','ผลลัพธ์','สาเหตุ'],
  'apparent':     ['ซ่อนเร้น','คลุมเครือ','ลึกลับ','ไม่ชัดเจน'],
  'despite':      ['เพราะว่า','เนื่องจาก','ดังนั้น','ในขณะที่'],
  'whereas':      ['เพราะว่า','ดังนั้น','นอกจากนี้','ยิ่งไปกว่านั้น'],
  'approximate':  ['แน่นอน','เกินจริง','ผิดพลาด','สมบูรณ์'],
  'diverse':      ['เหมือนกัน','เดียว','สม่ำเสมอ','แน่นอน'],
  'essential':    ['ไม่จำเป็น','ไม่สำคัญ','ไม่เกี่ยวข้อง','ทางเลือก'],
  'fundamental':  ['ผิวเผิน','ไม่สำคัญ','รอง','ชั่วคราว'],
  'guarantee':    ['ปฏิเสธ','สงสัย','คาดเดา','ทดสอบ'],
  'influence':    ['ไม่เกี่ยวข้อง','ป้องกัน','ขัดขวาง','ต่อต้าน'],
  'perception':   ['ความจริง','ข้อเท็จจริง','ผลลัพธ์','การพิสูจน์'],
  'resolve':      ['ปล่อยทิ้ง','หลีกเลี่ยง','ซับซ้อน','เพิกเฉย'],
  'strategy':     ['ความบังเอิญ','ผลลัพธ์','ปัญหา','ความสับสน'],
  'transition':   ['ความหยุดนิ่ง','ความคงที่','การยืนกราน','การปฏิเสธ'],
  'voluntary':    ['บังคับ','จำเป็น','ฝืนใจ','บีบบังคับ'],
  'widespread':   ['หายาก','จำกัด','เฉพาะที่','น้อยมาก'],
};

// ===== QUIZ QUESTIONS (grammar fill-in) =====
const GRAMMAR_QUESTIONS = [
  {
    word:'achieve', ipa:'/əˈtʃiːv/', topic:'Past Simple',
    sentence:'She ___ her goal after years of hard work.',
    options:['achieved','achieves','has achieved','was achieving'],
    answer:'achieved',
    explanation:'ใช้ Past Simple (V2) เพราะ "after years of hard work" บ่งบอกว่าเหตุการณ์นี้จบสมบูรณ์แล้วในอดีต',
  },
  {
    word:'negotiate', ipa:'/nɪˈɡəʊʃieɪt/', topic:'Present Perfect',
    sentence:'The two companies ___ a new agreement since last year.',
    options:['have negotiated','negotiated','are negotiating','will negotiate'],
    answer:'have negotiated',
    explanation:'ใช้ Present Perfect เพราะ "since last year" เชื่อมอดีตกับปัจจุบัน การเจรจายังมีผลถึงตอนนี้',
  },
  {
    word:'contribute', ipa:'/kənˈtrɪbjuːt/', topic:'Passive Voice',
    sentence:'Many useful ideas ___ by the students during the meeting.',
    options:['were contributed','contributed','have contributed','are contributing'],
    answer:'were contributed',
    explanation:'ใช้ Passive Voice (were + V3) เพราะ "ideas" คือสิ่งที่ถูกกระทำ ไม่ใช่ผู้กระทำ',
  },
  {
    word:'persist', ipa:'/pəˈsɪst/', topic:'Conditionals',
    sentence:'If she ___ with her training, she would become a champion.',
    options:['persisted','persists','had persisted','would persist'],
    answer:'persisted',
    explanation:'Second Conditional ใช้ V2 ใน if-clause เพื่อแสดงสถานการณ์สมมติที่ไม่น่าเป็นจริงในปัจจุบัน',
  },
  {
    word:'maintain', ipa:'/meɪnˈteɪn/', topic:'Modal Verbs',
    sentence:'You ___ a consistent study routine if you want to improve.',
    options:['should maintain','maintained','are maintaining','have maintained'],
    answer:'should maintain',
    explanation:'ใช้ Modal Verb "should" + V1 เพื่อแสดงคำแนะนำ โครงสร้างคือ Subject + modal + V1',
  },
  {
    word:'establish', ipa:'/ɪˈstæblɪʃ/', topic:'Past Simple',
    sentence:'The university ___ its first international programme in 1998.',
    options:['established','establishes','has established','was establishing'],
    answer:'established',
    explanation:'ใช้ Past Simple เพราะมีการระบุเวลาในอดีตชัดเจน "in 1998"',
  },
  {
    word:'analyze', ipa:'/ˈænəlaɪz/', topic:'Present Perfect',
    sentence:'The researchers ___ the data three times already.',
    options:['have analyzed','analyzed','are analyzing','will analyze'],
    answer:'have analyzed',
    explanation:'ใช้ Present Perfect เพราะ "already" บ่งบอกว่าทำเสร็จแล้วก่อนเวลาปัจจุบันและยังเกี่ยวข้องกับตอนนี้',
  },
  {
    word:'evaluate', ipa:'/ɪˈvæljueɪt/', topic:'Passive Voice',
    sentence:'The proposals ___ by the committee last Friday.',
    options:['were evaluated','evaluated','have been evaluated','are evaluating'],
    answer:'were evaluated',
    explanation:'ใช้ Passive Voice Past Simple เพราะ "committee" เป็นผู้กระทำ แต่ไม่ใช่ประธาน และมีบอกเวลา "last Friday"',
  },
];